package:
  name: corrfunc
  version: "2.0.0"

source:
  fn: corrfunc-2.0.0.tar.gz
  url: https://pypi.io/packages/source/c/corrfunc/corrfunc-2.0.0.tar.gz
  md5: 1ef4ba2d917929aede23efddfcfbc78a

build:
  number : 0
  script :
    - make install
    - python setup.py install

requirements:
  build:
    - python
    - numpy x.x
    - future
    - gsl

  run:
    - python
    - future
    - numpy x.x
    - gsl

test:
  files:
    - theory/tests/data/gals_Mr19.ff
    - mocks/tests/data/Mr19_mock_northonly.rdcz.dat
    - include/countpairs.h
    - include/countpairs_rp_pi_mocks.h
    - theory/tests/bins
    - mocks/tests/bins
    - mocks/tests/angular_bins
    - mocks/tests/data/Mr19_centers_xyz_forVPF_rmax_10Mpc.txt
  imports:
    - Corrfunc
    - Corrfunc._countpairs
    - Corrfunc._countpairs_mocks
    - Corrfunc.call_correlation_functions
    - Corrfunc.call_correlation_functions_mocks

  commands:
    - python -c "import Corrfunc.call_correlation_functions as c; c.main()"
    - python -c "import Corrfunc.call_correlation_functions_mocks as m; m.main()"

about:
  home: https://github.com/manodeep/Corrfunc
  license: MIT
  license_file: LICENSE
  summary: Blazing fast correlation functions on the CPU

extra:
  maintainers:
    - Manodeep Sinha <manodeep@gmail.com>
