## Shameless taken from scikit-image - 15th May, 2023 (MS)

name: Benchmark cron

on:
  schedule:
    - cron: '23 */6 * * * '
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  benchmark_linux:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "processes_1"
            asv-args: "-a processes=1"
          - name: "no_interleave"
            asv-args: "--no-interleave-processes"
          - name: "default"
            asv-args: "--interleave-processes -a processes=2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Setup some dependencies
        shell: bash -l {0}
        run:
          pip install asv

      - name: Run benchmarks
        shell: bash -l {0}
        run: |
          set -x

          # ID this runner
          asv machine --yes

          # Run benchmarks for last commit against previous one
          asv continuous ${{ matrix.asv-args }} --split --show-stderr 'HEAD^' 'HEAD'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: asv-benchmark-results-${{ matrix.name }}
          path: .asv/results
