name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make
    - name: install
      run: make install
    - name: tests
      run: make tests
    - name: python extensions
      run: python -m pip install -e .
