name: Integration Tests CI

on: [push, pull_request]

jobs:
  build:
    name: Integration tests with ${{ matrix.os }} with (${{ matrix.compiler }}, python-${{ matrix.python-version }}, numpy-${{ matrix.numpy-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        compiler: [gcc-8]
    env:
      CC: ${{ matrix.compiler }}
      CORRFUNC_CI: true
      INTEGRATION_TESTS: true
      CFLAGS: -DINTEGRATION_TESTS

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda create -q --yes -n test
          conda activate test
          conda install -q --yes -c conda-forge gsl

      - name: Display PATH, compiler, python
        shell: bash -l {0}
        run: |
          conda activate test
          echo "PATH = " $PATH
          echo "COMPILER = " `which ${{ matrix.compiler }}`
          echo "COMPILER VERSION = " `${{ matrix.compiler }} --version`
          echo "PYTHON = " `which python`
          echo "(PYTHON) version = " `python -c "import sys; print(sys.version);"`

      - name: compile
        shell: bash -l {0}
        run: make -r CC=${{ matrix.compiler }}

      - name: tests
        shell: bash -l {0}
        run: make tests CC=${{ matrix.compiler }}
